<!DOCTYPE html>
<html lang="" xml:lang="">
<head>
    <title></title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <br/>
    <style type="text/css">
        * {font-family: 'Times New Roman';}
        <!--
        p {margin: 0; padding: 0;}	.ft10{font-size:18px;color:#212121;}
        .ft11{font-size:18px;line-height:24px;color:#212121;}
        -->
    </style>
</head>
<body>
<div id="page1-div" style="position:relative;width:894px;height:1263px;">
    <p style="position:absolute;top:86px;left:499px;white-space:nowrap" class="ft11">Начальнику&#160;отдела&#160;организации<br/>культурно-массовой&#160;и<br/>организационной&#160;работы<br/>Г.Р.&#160;Шарапова</p>
    <p style="position:absolute;top:248px;left:345px;white-space:nowrap" class="ft10">Уважаемая&#160;Гузель&#160;Ринатовна!</p>
    <p style="position:absolute;top:298px;left:180px;white-space:nowrap" class="ft10">${concert_date}&#160;года&#160;${institute}</p>
    <p style="position:absolute;top:323px;left:128px;white-space:nowrap" class="ft11">организует&#160;и&#160;проводит&#160;конкурсную&#160;программу&#160;в<br/>рамках&#160;Ежегодного&#160;Фестиваля&#160;«День&#160;первокурсника»&#160;–&#160;2021».</p>
    <p style="position:absolute;top:397px;left:180px;white-space:nowrap" class="ft10">В&#160;связи&#160;с&#160;этим&#160;просим&#160;Вас&#160;рассмотреть&#160;возможность&#160;предоставления</p>
    <p style="position:absolute;top:422px;left:128px;white-space:nowrap" class="ft10">нам&#160;костюмов&#160;для&#160;выступления&#160;на&#160;${concert_date}</p>
    <p style="position:absolute;top:471px;left:180px;white-space:nowrap" class="ft10">Надеемся&#160;инициатива&#160;студенчества&#160;найдет&#160;поддержку&#160;в&#160;Вашем&#160;лице!</p>
    <p style="position:absolute;top:953px;left:128px;white-space:nowrap" class="ft10">Ответственный:&#160;${cultorg_surname}&#160;${cultorg_name}&#160;${cultorg_patronymic}</p>
    <p style="position:absolute;top:1040px;left:128px;white-space:nowrap" class="ft10">Зам.директора&#160;по&#160;СВР&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;${first_letter_deputy_name}&#160;${first_letter_deputy_patronymic}&#160;${deputy_surname}</p>
</div>
</body>
</html>