POST http://localhost:8080/file/concertApplication
Content-Type: application/json
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNzY3ODcsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.SUxYD11ddeiSnBGzqUb5Qmd6rinO9Gr22-B9s7mmGUo

{
  "institute" : "ITIS",
  "concertDate" : "06.10.2021",
  "cultorgName" : "Анна",
  "cultorgSurname" : "Будревич",
  "cultorgPatronymic" : "Дмитриевна",
  "cultorgClass" : "11-901",
  "cultorgPhone" : "89534014606",
  "producerName" : "Даниял",
  "producerSurname" : "Салахов",
  "producerPatronymic" : "Ильдарович",
  "producerClass" : "11-001",
  "producerPhone" : "88005553535",
  "deputyName" : "Айсылу",
  "deputySurname" : "Бакирова",
  "deputyPatronymic" : "Наримовна",
  "deputyPhone" : "88005555555",
  "dateInTheSmallHall" : "05.10.2021",
  "timeInTheSmallHall" : "16:00-21:00",
  "dateInTheBigHall" : "06.10.2021",
  "timeInTheBigHall" : "7:00-10:00"
}

###

POST http://localhost:8080/file/nightSetup
Content-Type: application/json
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNzU1NjYsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.nuEOSHRA2HztTmPmUjG34XoSzFv9txXYZ9bADlmWXYE

{
  "institute" : "ITIS",
  "concertDate" : "06.10.2021",
  "startDate" : "5.10.2021",
  "startTime" : "21:00",
  "finishDate" : "6.10.2021",
  "finishTime" : "6:00",
  "cultorgName" : "Анна",
  "cultorgSurname" : "Будревич",
  "cultorgPatronymic" : "Дмитриевна",
  "responsibleName" : "Даниял",
  "responsibleSurname" : "Салахов",
  "responsiblePatronymic" : "Ильдарович",
  "responsiblePhone" : "88005553535",
  "responsiblePosition" : "Заместитель директора по СВР",
  "deputyName" : "Айсылу",
  "deputySurname" : "Бакирова",
  "deputyPatronymic" : "Наримовна",
  "instituteInTheGenitive" : "Института информационных технологий и интеллектуальных систем"
}

###

POST http://localhost:8080/file/concertCostume
Content-Type: application/json
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNzU1NjYsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.nuEOSHRA2HztTmPmUjG34XoSzFv9txXYZ9bADlmWXYE

{
  "institute" : "ITIS",
  "concertDate" : "06.10.2021",
  "cultorgName" : "Анна",
  "cultorgSurname" : "Будревич",
  "cultorgPatronymic" : "Дмитриевна",
  "deputyName" : "Айсылу",
  "deputySurname" : "Бакирова",
  "deputyPatronymic" : "Наримовна"
}

###

POST http://localhost:8080/file/tehGroup
Content-Type: application/json
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNzU1NjYsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.nuEOSHRA2HztTmPmUjG34XoSzFv9txXYZ9bADlmWXYE

{
  "institute" : "ITIS",
  "startDate" : "5.10.2021",
  "startTime" : "21:00",
  "finishDate" : "6.10.2021",
  "finishTime" : "6:00",
  "responsibleName" : "Даниял",
  "responsibleSurname" : "Салахов",
  "responsiblePatronymic" : "Ильдарович",
  "responsiblePosition" : "Заместитель директора по СВР",
  "directorName" : "Айсылу",
  "directorSurname" : "Бакирова",
  "directorPatronymic" : "Наримовна",
  "instituteInTheGenitive" : "Института информационных технологий и интеллектуальных систем",
  "today" : "22.01.2022"
}

###

POST http://localhost:8080/sign-up
Content-Type: application/json

{
  "email" : "budrevichanya@gmail.com",
  "name" : "Anna",
  "surname" : "Budrevich",
  "institute" : "ITIS",
  "password" : "07072001",
  "repeatedPassword" : "07072001",
  "role" : "USER"
}

###

POST http://localhost:8080/sign-in
Content-Type: application/json

{
  "email" : "budrevichanya@gmail.com",
  "password" : "07072001"
}

###

POST http://localhost:8080/update
Content-Type: application/json
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNDQ3MjYsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.Ni-VD9eY3tYALyad_JZjTmgaYirReNnc_V2KIwWMpFA
R-TOKEN: 70e3513c-e38a-4136-b7f2-1f1baf6d05c6

###

POST http://localhost:8080/users/1/block
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNDk1MDIsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.TxvLtXind-L-LzrlKHnX511HnF1-QwfVIdgr9tFZPak

###

GET http://localhost:8080/logout
A-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwia2luZCI6IlVTRVIiLCJleHAiOjE2NDMxNDk2NjEsImVtYWlsIjoiYnVkcmV2aWNoYW55YUBnbWFpbC5jb20ifQ.kkMJt_koOnD6DL7aBoFT3qWFjysfxnpu1a0g4Wy_ctg